# Generated by Django 4.2.2 on 2023-09-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStock', '0002_proveedor_transportista_rename_codigo_producto_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.FloatField(),
        ),
    ]
